### ISSUE TITLE
Upload where the protocol doesn't support renaming fails

### ISSUE THREAD

**Issue by illingwo** [rucio/rucio#1506] opened 2018-08-29 15:16 UTC
Trying to upload a file when the protocol doesn't support renaming fails with

```$ rucio upload --rse MANCHESTER --scope user.illingwo /tmp/rucio_test_file3.txt 
2018-08-29 09:05:25,936	INFO	Preparing upload for file rucio_test_file3.txt
2018-08-29 09:05:25,989	INFO	Successfully added replica in Rucio catalogue at MANCHESTER
2018-08-29 09:05:26,054	INFO	Successfully added replication rule at MANCHESTER
2018-08-29 09:05:27,261	INFO	Trying upload with srm to MANCHESTER
2018-08-29 09:05:38,241	ERROR	list indices must be integers, not str
```

The reason is that in the no-renaming branch starting here https://github.com/rucio/rucio/blob/ef9aeac19f2f288bb4bdda4969e3710e27ea14ec/lib/rucio/rse/rsemanager.py#L449

the value of `ret` is updated if there's a problem, but it's not in the case of success. Since the return type depends on the length of `ret`, not setting it causes the index type error above. 

This looks very similar to #1487

**Comment by illingwo** [comment] 2018-08-29 15:30
After a closer look, I think it's exactly the same problem as #1487

**Comment by bari12** [comment] 2018-09-10 09:36
Ok, I will close this one as a Duplicate of #1487 then.

**Closed as completed by bari12** 2018-09-10 09:36 UTC
