### ISSUE TITLE
[conveyor] RSE filtering after query can starve results

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4510] opened 2021-03-31 03:00 UTC
In https://github.com/rucio/rucio/blob/644b42c35628061e8a3291ebaf44485c860ea982/lib/rucio/core/transfer.py#L1376-L1382
there is a filter after the query that enables conveyor-submitter to only act on a subset of RSEs. This path would be enabled if either of the daemon options https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/bin/rucio-conveyor-submitter#L106-L109 are used.

Suppose there is a large backlog from an RSE that is excluded, then if the query returns only `limit` (the `--bulk` option, default 100) results and all of them are from this RSE (either by chance, or, now thanks to #4375, if they are all the oldest) then all results the query returns will be discarded and we'll never see any results we can process.

I think this should be changed to instead filter at L1335 by adding, e.g.
```
if rses:
    sub_requests = sub_requests.filter(models.RSE.id.in_(rses))
```

**Comment by rcarpa** [comment] 2021-03-31 15:06
Looks like duplicate of #4405

**Closed as completed** 2021-06-25 07:16 UTC
