### ISSUE TITLE
Auditor does not work with certain HTTPS dumps

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#367] opened 2017-12-14 14:59 UTC
Motivation
----------
More detailed report on [ATLAS JIRA](https://its.cern.ch/jira/browse/RUCIO-2182)

**Comment by bbockelm** [comment] 2018-01-09 16:34
Duplicate of #429 ?

**Comment by bari12** [comment] 2018-01-12 15:33
Yes, I'll close the other one.

**Closed as completed** 2018-05-25 11:43 UTC
Labels: bug, Consistency checks
