### ISSUE TITLE
Core : config.set doesn't support anymore space character

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2262] opened 2019-02-27 11:00 UTC
Motivation
----------
```
>>> from rucio.core.config import set
>>> set(section='throttler', option='Data Consolidation,xyz', value=2000, session=None)
Control/space characters not allowed (key='has_option_throttler_Data Consolidation,xyz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 356, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/config.py", line 203, in set
    if not has_option(section=section, option=option, session=session):
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 288, in new_funct
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/config.py", line 129, in has_option
    has_option = REGION.get(has_option_key, expiration_time=expiration_time)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 665, in get
    value = self.backend.get(key)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/backends/memcached.py", line 161, in get
    value = self.client.get(key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 1121, in get
    return self._get('get', key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 1065, in _get
    self.check_key(key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 1320, in check_key
    "Control/space characters not allowed (key=%r)" % key)
memcache.MemcachedKeyCharacterError: Control/space characters not allowed (key='has_option_throttler_Data Consolidation,xyz')
```

**Comment by hahahannes** [comment] 2019-02-28 15:10
Can be closed as duplicate of #2128

**Closed as completed** 2019-02-28 15:11 UTC
Labels: bug, Core & Internals
