### ISSUE TITLE
list-rse-attributes crashes cli for staging endpoints

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#2258] opened 2019-02-26 14:46 UTC
Motivation
----------
Since the merge of #1842 `rucio list-rse-attributes` crashes for staging endpoints:
```
[15:45][twegner@lxplus113 ~]$ rucio --version
rucio 1.19.0.post2
[15:45][twegner@lxplus113 ~]$ rucio -v list-rse-attributes TAIWAN-LCG2_TAPE-STAGING
2019-02-26 15:45:25,391	DEBUG	Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.0.post2/bin/rucio", line 159, in new_funct
    return function(*args, **kwargs)
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.0.post2/bin/rucio", line 1479, in list_rse_attributes
    print(tabulate.tabulate(table, tablefmt='plain'))
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.0.post2/lib/python2.7/site-packages/tabulate.py", line 1301, in tabulate
    for c, ct, fl_fmt, miss_v in zip(cols, coltypes, float_formats, missing_vals)]
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.0.post2/lib/python2.7/site-packages/tabulate.py", line 768, in _format
    return format(float(val), floatfmt)
ValueError: invalid literal for float(): True

2019-02-26 15:45:25,391	ERROR	invalid literal for float(): True
2019-02-26 15:45:25,392	ERROR	Strange error: No section: 'policy'
```

Modification
------------

**Comment by cserf** [comment] 2019-04-29 13:31
The problem is with the value '1.0' that is not handled properly by `tabulate` :
 ```
>>> table = [(u'TAIWAN-LCG2_TAPE-STAGING:', 'True'), (u'is_stagingarea:', 'True'), (u'stresstestweight:', '1.0')]
>>> print(tabulate.tabulate(table, tablefmt='plain'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.5/lib/python2.7/site-packages/tabulate.py", line 1301, in tabulate
    for c, ct, fl_fmt, miss_v in zip(cols, coltypes, float_formats, missing_vals)]
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.19.5/lib/python2.7/site-packages/tabulate.py", line 768, in _format
    return format(float(val), floatfmt)
ValueError: could not convert string to float: True
```
vs :
```
>>> table = [(u'TAIWAN-LCG2_TAPE-STAGING:', 'True'), (u'is_stagingarea:', 'True'), (u'stresstestweight:', '1')]
>>> print(tabulate.tabulate(table, tablefmt='plain'))
TAIWAN-LCG2_TAPE-STAGING:  True
is_stagingarea:            True
stresstestweight:             1
```

or :
```
>>> table = [(u'TAIWAN-LCG2_TAPE-STAGING:', 'True'), (u'is_stagingarea:', 'True'), (u'stresstestweight:', '1,0')]
>>> print(tabulate.tabulate(table, tablefmt='plain'))
TAIWAN-LCG2_TAPE-STAGING:  True
is_stagingarea:            True
stresstestweight:          1,0
```

**Comment by TWAtGH** [comment] 2019-04-29 13:50
Sorry forgot to mention that I've debugged it already to this point. But I won't have time to look further into it ( @bari12 )

**Comment by bari12** [comment] 2019-04-29 13:52
@nikmagini @TomasJavurek can you please have a look on this issue. (See @cserf comment)

**Comment by cserf** [comment] 2019-04-29 14:12
BTW, the `Strange error: No section: 'policy'` will be fixed here :
https://github.com/rucio/rucio/issues/2514

**Comment by mlassnig** [comment] 2021-03-23 11:51
hmmm, i just tried this, and it already works on the master?

```
mlassnig@lxplus704:~ $ rucio -v list-rse-attributes NDGF-T1_DATAFJORD | grep stresstestweight
stresstestweight:        1.0
```

@cserf is this ticket obsolete?

**Closed as completed** 2021-03-23 15:27 UTC
Labels: bug, Clients, good first issue
