### ISSUE TITLE
Auditor is not able to handle dumps on non-SRM endpoint

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#429] opened 2018-01-09 13:30 UTC
Motivation
----------
Auditor is not able to handle dumps on non-SRM endpoint

Modification
------------
Enable the dump download for gsiftp and davs sites

**Comment by bari12** [comment] 2018-01-12 15:33
This is a duplicate of #367

**Comment by cserf** [comment] 2018-02-01 08:37
Actually that's a different problem than #367 . Reopening

**Closed as completed** 2018-05-29 11:42 UTC
Labels: enhancement, Consistency checks
