### ISSUE TITLE
Change the PK for the content_history table

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1777] opened 2018-11-14 12:15 UTC
Motivation
----------
The current Primary Key for `content_history` is based on `scope`, `name`, `child_scope`, `child_name`. Because of this, one cannot keep the history when a dataset is attached/detached multiple times.

Modification
------------
Change to another PK

**Comment by bari12** [comment] 2018-11-23 15:37
This is a duplicate of #1818 Closing

**Closed as completed by bari12** 2018-11-23 15:37 UTC
Labels: enhancement, feature, Core & Internals
