### ISSUE TITLE
Strange issue with conveyor-submitter not finding existing RSE

### ISSUE THREAD

**Issue by knservis** [rucio/rucio#3959] opened 2020-08-26 03:53 UTC
The following code return no result for me:
https://github.com/rucio/rucio/blob/55aadf45016fe5567be5ca481ad2d6f9d212e5e3/lib/rucio/core/rse.py#L275

unless I change it to:
```
query = session.query(models.RSE.id).filter_by(id=rse, vo=vo)
```
as the variable `rse` contains the rse id. I am not sure why that is or why the system needs to query for an id when it already has the id.. 

Given that this is a 'common' library, you will probably need to know the execution path, which is through:
https://github.com/rucio/rucio/blob/3e548f0a6b9de48b13480e236be122fb37bf0fbf/lib/rucio/daemons/conveyor/common.py#L484
and then:
https://github.com/rucio/rucio/blob/4cec8f5ac13c3ce1d37f8f0248f9b3697a70e190/lib/rucio/rse/rsemanager.py#L95

I simply executed:  
`bin/rucio-conveyor-submitter --run-once --bulk 1 --rses DEMO_RSE_1 DEMO_RSE_2`
to get there.

**Comment by patrick-austin** [comment] 2020-08-26 08:54
The issue is in `conveyor/common.py`, `get_rse_info` accepts both RSE names and IDs, but when it's not specified it assumes it's a name and then tries to get the ID later.

This should've been fixed in 1.23.4, but if you're not running that version you can fix it like [this](https://github.com/rucio/rucio/commit/f5578416bdfc071ebac14ca3cd2f64b669993597#diff-3f5585deec71dd52008ace7f1fba009cR504). The change you made in `get_rse_id()` may break other places where we only have the RSE name but not ID so should probably be reverted once it's fixed in `common.py`.

**Closed as completed** 2020-08-31 16:04 UTC
