### ISSUE TITLE
unexpected filename attribute instead fo child_name in  rucio upload

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#1158] opened 2018-05-14 18:39 UTC
Motivation
----------

```
[jww@lapa jww]$ rucio -H https://rucio-lb-int.cern.ch  --verbose  upload  --rse UKI-NORTHGRID-LANCS-HEP_SCRATCHDISK --scope user.jwalder data15and16_13TeV_r21_v01_p3180_somemissing_S2T1.root

2018-05-14 16:45:09,470 DEBUG   Extracting filesize (9515202649) and checksum (2b39b7ef) for file user.jwalder:data15and16_13TeV_r21_v01_p3180_somemissing_S2T1.root
2018-05-14 16:45:09,470 DEBUG   Automatically setting new GUID
2018-05-14 16:45:09,760 DEBUG   Using account jwalder
2018-05-14 16:45:09,760 DEBUG   Skipping dataset registration
2018-05-14 16:45:09,760 DEBUG   Processing file user.jwalder:data15and16_13TeV_r21_v01_p3180_somemissing_S2T1.root for upload
2018-05-14 16:45:09,940 ERROR   A Rucio exception occurred when registering a file replica in Rucio.
2018-05-14 16:45:09,940 ERROR   A Rucio exception occurred when processing a file for upload.
2018-05-14 16:45:09,941 ERROR   Provided object does not match schema.
Details: Problem validating dids : Additional properties are not allowed (u'filename' was unexpected)

Failed validating 'additionalProperties' in schema['items']:
    {'additionalProperties': False,
     'description': 'Data Identifier(DID)',
     'properties': {'adler32': {'description': 'adler32',
                                'pattern': '^[a-fA-F\\d]{8}$',
                                'type': 'string'},
                    'bytes': {'description': 'Size in bytes',
                              'type': 'integer'},
                    'md5': {'description': 'md5',
                            'pattern': '^[a-fA-F\\d]{32}$',
                            'type': 'string'},
                    'meta': {'additionalProperties': True,
                             'description': 'Data Identifier(DID) metadata',
                             'properties': {'guid': {'description': 'Universally Unique Identifier (UUID)',
                                                     'pattern': '^(\\{){0,1}[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}(\\}){0,1}$',
                                                     'type': 'string'}},
                             'type': 'object'},
                    'name': {'description': 'Data Identifier name',
                             'pattern': '^[A-Za-z0-9][A-Za-z0-9\\.\\-\\_]{1,250}$',
                             'type': 'string'},
                    'pfn': {'description': 'Physical File Name',
                            'type': 'string'},
                    'rules': {'description': 'Array of replication rules',
                              'items': {'additionalProperties': False,
                                        'description': 'Replication rule',
                                        'properties': {'account': {'description': 'Account name',
                                                                   'pattern': '^[a-z0-9-_]{1,30}$',
                                                                   'type': 'string'},
                                                       'activity': {'description': 'Activity name',
                                                                    'enum': ['Data Brokering',
                                                                             'Data Consolidation',
                                                                             'Data rebalancing',
                                                                             'Debug',
                                                                             'Express',
                                                                             'Functional Test',
                                                                             'Functional Test XrootD',
                                                                             'Functional Test WebDAV',
                                                                             'Group Subscriptions',
                                                                             'Production Input',
                                                                             'Production Output',
                                                                             'Analysis Input',
                                                                             'Analysis Output',
                                                                             'Staging',
                                                                             'T0 Export',
                                                                             'T0 Tape',
                                                                             'Upload/Download (Job)',
                                                                             'Upload/Download (User)',
                                                                             'User Subscriptions'],
                                                                    'type': 'string'},
                                                       'ask_approval': {'description': 'Rule approval request',
                                                                        'type': ['boolean',
                                                                                 'null']},
                                                       'asynchronous': {'description': 'Asynchronous rule creation',
                                                                        'type': ['boolean',
                                                                                 'null']},
                                                       'comment': {'description': 'Rule comment',
                                                                   'maxLength': 250,
                                                                   'type': ['string',
                                                                            'null']},
                                                       'copies': {'description': 'Number of replica copies',
                                                                  'type': 'integer'},
                                                       'dids': {'type': 'array'},
                                                       'grouping': {'description': 'Rule grouping',
                                                                    'enum': ['DATASET',
                                                                             'NONE',
                                                                             'ALL',
                                                                             None],
                                                                    'type': ['string',
                                                                             'null']},
                                                       'ignore_availability': {'description': 'Rule ignore availability status',
                                                                               'type': 'boolean'},
                                                       'lifetime': {'description': 'Rule lifetime',
                                                                    'type': ['number',
                                                                             'null']},
                                                       'locked': {'description': 'Rule locked status',
                                                                  'type': ['boolean',
                                                                           'null']},
                                                       'meta': {'description': 'Rule wfms metadata',
                                                                'maxLength': 3999,
                                                                'type': ['string',
                                                                         'null']},
                                                       'notify': {'description': 'Rule notification setting',
                                                                  'enum': ['Y',
                                                                           'C',
                                                                           'N',
                                                                           None],
                                                                  'type': ['string',
                                                                           'null']},
                                                       'priority': {'description': 'Priority of the transfers',
                                                                    'type': 'integer'},
                                                       'purge_replicas': {'description': 'Rule purge replica status',
                                                                          'type': 'boolean'},
                                                       'rse_expression': {'description': 'RSE expression',
                                                                          'type': 'string'},
                                                       'source_replica_expression': {'description': 'RSE expression',
                                                                                     'type': ['string',
                                                                                              'null']},
                                                       'split_container': {'description': 'Rule split container mode',
                                                                           'type': ['boolean',
                                                                                    'null']},
                                                       'subscription_id': {'description': 'Rule Subscription id',
                                                                           'type': ['string',
                                                                                    'null']},
                                                       'weight': {'description': 'Rule weight',
                                                                  'type': ['string',
                                                                           'null']}},
                                        'required': ['dids',
                                                     'copies',
                                                     'rse_expression'],
                                        'type': 'object'},
                              'maxItems': 1000,
                              'minItems': 1,
                              'type': 'array'},
                    'scope': {'description': 'Scope name',
                              'pattern': "^[a-zA-Z'_'-.0-9]{1,25}$",
                              'type': 'string'},
                    'state': {'description': 'Replica state',
                              'enum': ['AVAILABLE',
                                       'UNAVAILABLE',
                                       'COPYING',
                                       'BEING_DELETED',
                                       'BAD',
                                       'SOURCE',
                                       'A',
                                       'U',
                                       'C',
                                       'B',
                                       'D',
                                       'S'],
                              'type': 'string'},
                    'type': {'description': 'DID type',
                             'enum': ['DATASET',
                                      'CONTAINER',
                                      'FILE',
                                      'F'],
                             'type': 'string'}},
     'required': ['scope', 'name'],
     'type': 'object'}
On instance[0]:
    {u'adler32': u'2b39b7ef',
     u'bytes': 9515202649,
     u'filename': u'data15and16_13TeV_r21_v01_p3180_somemissing_S2T1.root',
     u'meta': {u'guid': u'afd7beb380714e5fb2197c005faadc63'},
     u'name': u'data15and16_13TeV_r21_v01_p3180_somemissing_S2T1.root',
     u'scope': u'user.jwalder',
     u'state': u'C'}
Completed in 26.2589 sec.
```

**Comment by bari12** [comment] 2018-05-15 09:01
I think for this it should be fine if `filename` gets added to the schema. (This is related to the change Brian did to be able to have filenames different than the `name`) 
I am just wondering why this only shows up now or if basically no `rucio upload` works since this? @mlassnig @vingar Can one of you please fix this so we have it in the release next week?

**Comment by cserf** [comment] 2018-07-20 13:41
@TomasJavurek , @TWAtGH  isn't it fixed ?

**Comment by bari12** [comment] 2018-07-26 12:51
I tried to reproduce this but can't. Closing

**Closed as completed by bari12** 2018-07-26 12:51 UTC
Labels: bug, Core & Internals, Clients
