### ISSUE TITLE
Create documentation page for S3-type storage

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5450] opened 2022-04-05 14:53 UTC
Motivation
----------

Modification
------------
https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE

**Comment by rizart** [comment] 2022-10-14 21:26
Closing this as a duplicate of https://github.com/rucio/documentation/issues/159.

**Closed as completed by rizart** 2022-10-14 21:26 UTC
Labels: feature, Documentation, Protocols
