### ISSUE TITLE
bug in rucio client with --summary and --pfn

### ISSUE THREAD

**Issue by wguanicedew** [rucio/rucio#1360] opened 2018-07-18 14:05 UTC
Motivation
----------
When uploading files to objectstore with --pfn. It can work. But if adding --summary, the file will be uploaded successfully but it fails to print the summary. Maybe it has some problem to get summary from --pfn.

[wguan@lxplus007 ~]$ which rucio
/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.16.4/bin/rucio
[wguan@lxplus007 ~]$ export S3_ACCESS_KEY=KJE7GOEQJVSAWDKPK4MA; export S3_SECRET_KEY=*****; export S3_IS_SECURE=True; /usr/bin/env rucio -v upload --rse CERN-PROD_ES --scope transient --no-register --pfn s3://cs3.cern
.ch:443//atlas-eventservice/05cc36b8-383f-444f-a384-592fad3b918e /bin/hostname 
2018-07-18 16:02:03,903 DEBUG   PFN option specified, extracting protocol from given PFN: s3
2018-07-18 16:02:03,905 DEBUG   Extracting filesize (13880) and checksum (ed26537c) for file transient:hostname
2018-07-18 16:02:03,905 DEBUG   Automatically setting new GUID
2018-07-18 16:02:04,019 DEBUG   Using account wguan
2018-07-18 16:02:04,019 DEBUG   Skipping dataset registration
2018-07-18 16:02:04,020 DEBUG   Processing file transient:hostname for upload
2018-07-18 16:02:04,065 DEBUG   Uploading source file to RSE
2018-07-18 16:02:07,079 INFO    File transient:hostname successfully uploaded on the storage
2018-07-18 16:02:07,079 DEBUG   sending trace
2018-07-18 16:02:07,115 DEBUG   Finished uploading files to RSE.
Completed in 3.4517 sec.
[wguan@lxplus007 ~]$ export S3_ACCESS_KEY=KJE7GOEQJVSAWDKPK4MA; export S3_SECRET_KEY=******; export S3_IS_SECURE=True; /usr/bin/env rucio -v upload --rse CERN-PROD_ES --scope transient --no-register --summary --pfn s3://cs3.cern.ch:443//atlas-eventservice/05cc36b8-383f-444f-a384-592fad3b918e /bin/hostname 
2018-07-18 16:02:21,171 DEBUG   PFN option specified, extracting protocol from given PFN: s3
2018-07-18 16:02:21,172 DEBUG   Extracting filesize (13880) and checksum (ed26537c) for file transient:hostname
2018-07-18 16:02:21,172 DEBUG   Automatically setting new GUID
2018-07-18 16:02:21,262 DEBUG   Using account wguan
2018-07-18 16:02:21,263 DEBUG   Skipping dataset registration
2018-07-18 16:02:21,263 DEBUG   Processing file transient:hostname for upload
2018-07-18 16:02:21,291 DEBUG   Uploading source file to RSE
2018-07-18 16:02:22,766 INFO    File transient:hostname successfully uploaded on the storage
2018-07-18 16:02:22,767 DEBUG   sending trace
2018-07-18 16:02:22,805 DEBUG   Finished uploading files to RSE.
2018-07-18 16:02:22,834 ERROR   list indices must be integers, not str
2018-07-18 16:02:22,834 DEBUG   This means the parameter you passed has a wrong type.
Completed in 1.7402 sec.

Modification
------------

**Comment by bari12** [comment] 2018-07-23 13:10
@TomasJavurek or @TWAtGH can one of you please have a look on this?

**Comment by bari12** [comment] 2018-07-23 13:11
Also adding @nikmagini as he had a look on the email already 😄

**Comment by TWAtGH** [comment] 2018-09-13 08:52
We werent able to reproduce this and the problem is probably solved with 1.17 because the upload code was completely overhauled.
So I'm closing this issue.

**Closed as completed by TWAtGH** 2018-09-13 08:52 UTC
Labels: bug, Clients

**Comment by vingar** [comment] 2018-09-13 08:59
I got the problem with 1.17.7. In my case, It was due to the rsemgr sending back a different value then the expected one. I vaguely remember a dict with True instead of something else.  One side remark, The logging in the debug mode of the traceback error showing where the error is exactly happening in the upload function is missing and will be more than useful.

**Comment by TWAtGH** [comment] 2018-09-13 09:15
Good call thanks. I've fixed it with #1533 There were also another bug.
