### ISSUE TITLE
download_method_problem

### ISSUE THREAD

**Issue by amanousak** [rucio/rucio#4665] opened 2021-06-09 08:23 UTC
Motivation
----------
I am trying to download  MC root files in order to test a new HLTrigger. Here is the script that I am using:
rucio --verbose download --dir /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/arkadios/TrigMuon_test/ruciofiles --allow-tape cms:/JpsiToMuMu_JpsiPt8_TuneCP5_14TeV-pythia8/Run3Winter20DRMiniAOD-DRFlatPU30to80_110X_mcRun3_2021_realistic_v6-v1/GEN-SIM-RAW#5ff8a0e4-2922-4921-9563-db2ea48c73a4
but the answer is
2021-06-09 10:13:23,005	ERROR	[Errno 13] Permission denied: '/JpsiToMuMu_JpsiPt8_TuneCP5_14TeV-pythia8'
2021-06-09 10:13:23,006	ERROR	
Rucio exited with an unexpected/unknown error.

Modification
------------

**Comment by cserf** [comment] 2021-06-09 11:11
Probably the same problem as https://github.com/rucio/rucio/issues/3031

**Comment by bari12** [comment] 2021-07-02 15:38
Could be the same as #3031, but I guess that means that no `rucio download` works for CMS, since they always have slashes in the did names? @nsmith- ?

**Comment by nsmith-** [comment] 2021-07-02 15:52
We don't use `rucio download` anywhere in production. In principle though such a command should be supported for CMS users. For now I would suggest making a rule to copy the data to T2 CERN (if it is not already on disk) and then accessing it using xrootd.

**Comment by bari12** [comment] 2021-07-02 16:12
Ok, then I agree, it's very likely that this is a duplicate of #3031

**Comment by amanousak** [comment] 2021-07-02 21:04
I made a rule to copy the data to T2 CERN and the problem was solved.Thanks a lot!!

**Closed as completed** 2021-07-21 15:57 UTC
Labels: bug, Clients
