### ISSUE TITLE
Object is missing this property: 'bytes' when querying for rules

### ISSUE THREAD

**Issue by labkode** [rucio/rucio#6518] opened 2024-02-28 10:03 UTC
### Description

An error is given when trying to get the rules of a FILE using the ``--file`` flag.
See below.

```
[user@client ~]$ rucio ls test:file1
+--------------+--------------+
| SCOPE:NAME   | [DID TYPE]   |
|--------------+--------------|
+--------------+--------------+
[user@client ~]$ rucio ls --filter 'type=all' test:file1
+--------------+--------------+
| SCOPE:NAME   | [DID TYPE]   |
|--------------+--------------|
| test:file1   | DIDType.FILE |
+--------------+--------------+
[user@client ~]$ rucio list-rules test:file1
ID                                ACCOUNT    SCOPE:NAME    STATE[OK/REPL/STUCK]    RSE_EXPRESSION    COPIES    SIZE       EXPIRES (UTC)    CREATED (UTC)
--------------------------------  ---------  ------------  ----------------------  ----------------  --------  ---------  ---------------  -------------------
6c4f62b08c084f35a37bd620770733c1  root       test:file1    OK[1/0/0]               XRD1              1         10.486 MB                   2024-02-28 09:23:08
[user@client ~]$ rucio list-rules --file test:file1
2024-02-28 09:59:34,190 ERROR
The object is missing this property: 'bytes'
This should never happen. Please rerun the last command with the "-v" option to gather more information.
Please follow up with all relevant information at: https://github.com/rucio/rucio/issues/
````

### Steps to reproduce

Following K8s tutorial.
Just create the file and run the previous command

### Rucio Version

Client: 33.6.0

### Additional Information

K8s deployment (minikube)

**Comment by dchristidis** [comment] 2024-02-28 10:12
Duplicate of #6348.

**Closed as not planned by dchristidis** 2024-02-28 10:12 UTC
Labels: bug
