### ISSUE TITLE
Rule Re-evaluation for existing locks

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6956] opened 2024-07-19 12:08 UTC
### Description

Introduce a `re-evaluate rule` command that can re-evaluate the decisions made during the injection (rule creation) stage. i.e. to create new locks and delete old ones based on current rse availabilities and configurations.  

For the time being, having the ability to issue a command manually should be enough to take care of operational needs.
For the future, if there are no undesirable side effects, having a policy-based rule re-evaluation (such as re-evaluate after 15 days of being `STUCK` etc.) might be considered.

**Note**: Clarification on Terminology :
Currently, a `re-evaluation` by `rucio-judge-evaluator` represents the creation of possible locks and replicas for files on new attachment or detachment operation to the container on which the rule exists. This issue overloads the terms to mean re-evaluating the existing locks.

### Motivation

Often sites are down with indeterminate time to return to normal operations. 
In situations that allow (multi-rse rse-expressions) operators would benefit from re-evaluating certain rules that possibly need to be completed due to various reasons.

Moving rules to new RSE expressions is not desirable as workload management and other systems track rule IDs and their status. Changing the expression to exclude a single RSE is not desirable in itself. 

FYI @bari12

**Comment by bari12** [comment] 2024-07-26 14:44
This is a duplicate of #536 
@dynamic-entropy can you please add the information to the other ticket. It's a very old ticket and we struggled every time we approached the issue, because it's not absolutely clear what the command should do and often comes down to a policy decision. Perhaps we can reduce all that to some minimal version of the command and start there though.

**Closed as completed by bari12** 2024-07-26 14:44 UTC
Labels: enhancement
