### ISSUE TITLE
Writing to tape: Destination file exists and overwrite is not enable

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#4447] opened 2021-03-18 07:16 UTC
Motivation
----------

https://ggus.eu/index.php?mode=ticket_info&ticket_id=151016

> This pattern shows us a problem in the Rucio / FTS interaction when writing to TAPE.
> If FTS encounters a problem that would lead to data being successfully copied to tape, but the transfer marked as FAILED, Rucio will keep retrying it.
> 
> Rucio doesn't use overwrite when writing to TAPE (for good reason).
> FTS won't be able to copy the file again because it exists already (expected behavior).
> 
> But this leaves us in a bad spot where the file will be retried continuously.
> 
> FTS doesn't have "file-reuse" functionality. 
> E.g.: when attempting a transfer, check if the file is at the destination already.

**Comment by bari12** [comment] 2021-03-18 08:12
There is a few different things we can try here, but the copy + rename workflow is already in place for cases like this, I wonder if this wouldn't just be the easiest solution.

**Comment by ericvaandering** [comment] 2021-03-22 16:37
If I understand what you're suggesting, that just doesn't work for CMS. DIDs are Logical file names and LFNs are the same across all of CMS. LFNs are matched to physical file names by simple algorithms so there is no opportunity to modify the LFN<->PFN correspondence.

**Comment by cserf** [comment] 2021-04-05 12:39
See also https://github.com/rucio/rucio/issues/4303
Belle II has the same problem (no possibility to modify the LFN to PFN correspondance). For now we have a cron job to identify the file replicas that are in state `REPLICATING` and if there is already a replica registered into the storage namespace it is renamed to something else. On the next attempt, the conveyor will be able to copy the file. Maybe the same logic can be applied in the conveyor.

**Comment by bari12** [comment] 2021-04-06 08:58
Understood.

I think we have a few options:
1. Enable overwrite on tape as @cserf suggested in #4303 
2. FTS implements some kind of file-reuse policy where it checks if a file is in place, checks if the checksum/size is correct, and marks the job as success in that case. Not sure how easy that is. Maybe Mihai can comment.
3. We do step (2) within Rucio. I would really like to avoid this though, since we do not have any physical replica interactions in these transfer loops. So starting this is an entire new thing to add.

**Comment by mpatrascoiu** [comment] 2021-04-09 07:14
Hello Martin,

Regarding your point 2, it's something I'm considering here: [FTS-1702](https://its.cern.ch/jira/browse/FTS-1702)
This will be implemented only for `check-on-tape` transfers, however.

Cheers,
Mihai

**Comment by bari12** [comment] 2021-04-09 17:47
Hi Mihai,

Thanks. I think this is a good solution in combination with #4303 for communities which do not use the `check-on-tape` feature. I would propose closing this then, unless somebody else has any comments.

**Comment by cserf** [comment] 2021-04-14 07:23
About the overwrite option, there is still the risk of a race condition where 2 FTS jobs are submitted to write the same file and one succeeds whereas the other one fails, so I'm not sure that we want to use this option for the endpoints storing RAW datasets.

**Comment by bari12** [comment] 2021-04-14 10:36
For endpoints storing raw we should use `check-on-tape` as well :-)

**Comment by iueda** [comment] 2021-04-14 13:29
> 1. Enable overwrite on tape as @cserf suggested in #4303

This can be made as an option, but still dangerous as @cserf suggests, and I may use it for some special tape endpoints, but wouldn't use it in general, especially for the tape endpoint for raw data.

> 2. FTS implements some kind of file-reuse policy where it checks if a file is in place, checks if the checksum/size is correct, and marks the job as success in that case.

What happens if the file size/checksum does not match? 
Would it remove it? Again it is dangerous.

The safest is what @cserfon has sugested:
If such errors "Destination file exists and overwrite is not enabled" are observed, one can rename the existing destination file to something else, so that the file on tape is not removed, and the next transfer attempt would not see the destination file.
This renaming can be done outside of Rucio, as @cserf is doing, but better be in Rucio, not in FTS, because Rucio can be sure if the file is being transferred or not. FTS cannot be sure if there is a transfer on-going by another FTS instance.

At least Rucio better not retry when such an error is returned, rather than keeping trying and reproducing transfer errors, considering it as a permanent failure.

**Comment by bari12** [comment] 2021-04-14 14:27
> > 1. Enable overwrite on tape as @cserf suggested in #4303
> 
> This can be made as an option, but still dangerous as @cserf suggests, and I may use it for some special tape endpoints, but wouldn't use it in general, especially for the tape endpoint for raw data.

It wouldn't be default, just an option as suggested by Cedric. But I think it is a good option to have, depending how you a community uses tape/what data they put there.

> > 1. FTS implements some kind of file-reuse policy where it checks if a file is in place, checks if the checksum/size is correct, and marks the job as success in that case.
> 
> What happens if the file size/checksum does not match?
> Would it remove it? Again it is dangerous.
> 
> The safest is what @cserfon has sugested:
> If such errors "Destination file exists and overwrite is not enabled" are observed, one can rename the existing destination file to something else, so that the file on tape is not removed, and the next transfer attempt would not see the destination file.
> This renaming can be done outside of Rucio, as @cserf is doing, but better be in Rucio, not in FTS, because Rucio can be sure if the file is being transferred or not. FTS cannot be sure if there is a transfer on-going by another FTS instance.

That's not true unfortunately. The cases where we have these 2 competing transfers are because Rucio doesn't know. This usually happens because you try to submit a transfer but the FTS call times out/doesn't give a response but was actually accepted by FTS. Now there is some protection for these cases, but it can still happen and you can still end up with 2 competing transfers.

**Comment by bari12** [comment] 2021-04-14 14:57
Let me summarise here a bit:
* If you use non-deterministic RSEs, this is not an issue as Rucio will use a unique URL (with a timestamp) and just register that one on success - That's why ATLAS does not see that issue. https://github.com/rucio/rucio/blob/876a844807c215529fc1c93010d454bcd3be75e1/lib/rucio/core/transfer.py#L821
* If you use deterministic RSE Tapes, as Belle and CMS do, this doesn't work
  * Enabling overwrite will solve it, but is dangerous and should only be used in specific cases
  * Solving this in FTS within the `check-on-tape` workflow works, but obviously doesn't work for anyone who doesn't use `check-on-tape`

For the remainder:
After thinking about this a bit, I believe the workflow would work as @cserf and @iueda suggest: On a failure on such an RSE immediately rename/delete the file and then retry. I think that would work even in the case of racing transfers, because only one of them would actually fly, the other one would get a failure due to not being able to overwrite. If that is the transfer Rucio thinks it submitted, it will rename/delete (Possibly fail doing that) and re-submit the transfer. But eventually that workflow should terminate positively.

**Comment by iueda** [comment] 2021-04-15 02:24
Right, I agree with @bari12 

> If that is the transfer Rucio thinks it submitted, it will rename/delete (Possibly fail doing that) and re-submit the transfer.

We have observed a case where the destination file is "locked" by SRM, which not only prevented Rucio from overwriting, but also prevented us from removing/renaming the file. Then, this requires some manual intervention, or at least some longer waiting time until SRM releases the file.

This suggests the need of Rucio's error handling as I suggested before:
> Rucio better not retry when such an error is returned, rather than keeping trying and reproducing transfer errors, considering it as a permanent failure.
Or, Rucio can retry, but with a larger interval than usual.

> But eventually that workflow should terminate positively.

True unless SE locks the file... (no more SRM in future, but we never know what mechanism makes such a lock).

**Comment by beer4duke** [comment] 2021-05-05 20:35
2 cents from cold storage endpoints:

>     1. Enable overwrite on tape as @cserf suggested in #4303

This is nice an safe, but for tape endpoints... If these false negative happen too often (failed when file is on tape) and you delete them and send the same file over you will end up with tapes full of holes that sites will have to repack. File reuse would be kind of nice for tapes...

Would be interesting to have an idea of the `file already exist` error occurrence (for users who have LFN = PFN) and file renaming occurance for others.

Second case leaves dark data on tape instead of holes some can say it is worse ;)

Tip: once removed dark data leaves exactly the same holes on tapes as overwrite for others and it is as inefficient as holes for recalls. Partial conclusion would be to address both issues together when transfers are failing.

>     2. FTS implements some kind of file-reuse policy where it checks if a file is in place, checks if the checksum/size is correct, and marks the job as success in that case. Not sure how easy that is. Maybe Mihai can comment.

Could be interesting if entirely isolated from the standard FTS use case (`file already exists` is an error if no overwrite) introducing unexpected corner case behavior just to reuse existing flags is certainly not what we want...
A dedicated `file reuse if filename and size and checksum are the same and this is what I really want` flag is maybe needed to clearly split responsibilities.

This is kind of safer than removing ESP on a supercar.
 
>     3. We do step (2) within Rucio. I would really like to avoid this though, since we do not have any physical replica interactions in these transfer loops. So starting this is an entire new thing to add.

More md info from source + dest files on FTS jobs? but nailing dark data may require a bit of 3. too... Or streamlining endpoint ns validation (with more than filenames).

**Comment by mlassnig** [comment] 2021-05-06 08:14
If I understood correctly, the approach without breaking backwards compatibility would be:

1. Introduce a new FTS job flag, e.g., `overwrite_verify: True|False`, that if true, queries the destination for the correctness of the potential destination file.

2. Adapt the FTS logic like this:

```
if not overwrite:
     if overwrite_verify:
         FTS_JOB_OK             # new feature
     else:
         FTS_JOB_NOT_OK    # existing backwards compatible behaviour
```

3. In Rucio, set `overwrite_verify=True` upon a transfer-request retry (so not on the first one).

This would solve the dark data problem and tape hole problem.

**Comment by bari12** [comment] 2021-05-06 13:36
If this is an option for FTS, than I think it would be the way to go. But from @mpatrascoiu I understood that it is only an option for `check-on-tape` transfers, which I am not sure if e.g. Belle II could use?

**Comment by beer4duke** [comment] 2021-05-24 20:05
After the meeting we had together, I volunteered to do a recap of the solution we agreed.
It took a bit more time as I needed to review the low level bits but here it is!

# Dealing with `Destination file exists and overwrite is not enabled` FTS Error reason

This is a problem for CMS because of its LFN=PFN mapping.

When a transfer leaves a file at its destination, Rucio will retry forever the transfer without the overwrite flag and all successive retries will fail until a CMS operator takes manual action to validate the file or remove it if invalid.

For CMS, the operator validation simply consist of checking the file Adler32 checksum and its file size.

If these 2 are OK, the file is validated on the destination in Rucio namespace, otherwise the destination file is deleted and the next retry will fix it (or not...).

The problem with these automatic infinite Rucio retries is that they amplify the problem: 2000 files generated more than 500k error messages over few days (aka monitoring DoS).

This could be easily automated by adapting slightly FTS reply and Rucio behaviour.


## FTS expanded behaviour

Currently such a failing job returns the following `file_metadata` field:

```json
{
  "dst_type": "TAPE",
  "name": "/store/mc/RunIISummer20UL18MiniAOD/TTToSemiLeptonic_mtop169p5_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/240000/2CA24833-6D0B-954B-B911-29EC334AE83C.root",
  "adler32": "453dc8ce",
  "source_globus_endpoint_id": null,
  "src_rse": "T2_CH_CERN",
  "activity": "Production Output",
  "src_rse_id": "542ab69d82bf401e9218bbe375bb1fce",
  "request_id": "14271d0479cb47729230abd00e4accce",
  "request_type": "TRANSFER",
  "filesize": 4189582710,
  "dest_rse_id": "f44c866a264d4da9972969e9f3b5bb52",
  "scope": "cms",
  "dst_rse": "T0_CH_CERN_Tape",
  "src_type": "DISK",
  "dest_globus_endpoint_id": null,
  "verify_checksum": "both",
  "md5": null
}
```

It could be extended to include `dst_file` metadata:
```json
{
  "dst_type": "TAPE",
  "name": "/store/mc/RunIISummer20UL18MiniAOD/TTToSemiLeptonic_mtop169p5_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/240000/2CA24833-6D0B-954B-B911-29EC334AE83C.root",
  "adler32": "453dc8ce",
  "source_globus_endpoint_id": null,
  "src_rse": "T2_CH_CERN",
  "activity": "Production Output",
  "src_rse_id": "542ab69d82bf401e9218bbe375bb1fce",
  "request_id": "14271d0479cb47729230abd00e4accce",
  "request_type": "TRANSFER",
  "filesize": 4189582710,
  "dest_rse_id": "f44c866a264d4da9972969e9f3b5bb52",
  "scope": "cms",
  "dst_rse": "T0_CH_CERN_Tape",
  "src_type": "DISK",
  "dest_globus_endpoint_id": null,
  "verify_checksum": "both",
  "md5": null,
  "dst_file": {
    "path": "/eos/ctacms/archive/cms/store/mc/RunIISummer20UL18MiniAOD/TTToSemiLeptonic_mtop169p5_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/240000/2CA24833-6D0B-954B-B911-29EC334AE83C.root",
    "exists": true,
    "path_exists": true,
    "on_tape": true,
    "online": false,
    "requested": false,
    "has_reqid": false,
    "req_time": "",
    "error_text": "",
    "filesize": 4189582710,
    "adler32": "453dc8ce"
  }
}
```

`dst_file` metadata will follow xrootd query prepare metadata (same as the future HTTP file metadata query format).

> :warning: filesize and adler32 key names are not finalized yet. More will come in [EOS-4714](https://its.cern.ch/jira/browse/EOS-4714)

**FTS job behaviour is unchanged: the job is still failed and returns `Destination file exists and overwrite is not enabled` error.**

This extension only provides enough information about the destination file to allow Rucio to decide to validate the destination file.

In the case of CMS such a failed job metadata would allow Rucio to validate the dst_file on eosctacms instance:
- this job is a checkOnTape job
   - `Archive timeout: 86400`
- the file `exists`, is `on_tape` and checksum and size are OK


## Rucio logic

**There should be a new Rucio configuration entry to override failed FTS transfer and enable validation with checksum and size.**

If this option is enabled the following logic will be used for failed transfers with `Destination file exists and overwrite is not enabled` error:

![image](https://user-images.githubusercontent.com/6848916/119401239-862eb600-bcdb-11eb-8497-1547cdd77299.png)

One additional option is needed to decide if Rucio should overwrite files with invalid checksum and size. **If not enabled only a manual operation can stop the infinite look: operator deleting the corrupted file.**

If the file is not yet on tape it is enough for Rucio to resubmit the exact same job: the file will eventually make it to tape and at that moment it will be validated.

The simple idea here is to mimic the FTS polling logic in Rucio retry mechanism.

In order to automatically purge corrupted files from the system Rucio should resubmit the transfer with overwrite set to true.

**Comment by bari12** [comment] 2021-05-25 13:21
Thanks a lot for the summary @beer4duke 
As mentioned during the discussion, I think the solution is good and we can add this validation on Rucio side and also add a couple of options for fine-grained control. I believe implementation wise this should not be too much effort, the only possible issue (within Rucio) might be the overwrite_on_retry because I am not 100% sure if retry-requests know that they are retry-requests. But that's something we can solve internally then.

The `dst_file` metadata will generally be available, not only for `check-on-tape` jobs I assume?

Maybe @cserf and @iueda can comment as well from the Belle II side.

**Comment by mpatrascoiu** [comment] 2021-05-25 13:32
Hello Martin,

I'm inclined to make this `dst_file` metadata available only on `check-on-tape` or introduce another particular flag (e.g.: `--file-integrity-report`).

There's a lot of overhead with this operation and no easy way to simplify it across the supported protocols. Although CTA provides all the necessary info in one `xrootd query prepare` call, there's no equivalent for that in SRM. At its worst, FTS would have to emit `stat` + `checksum` + `xattr user.status` calls and compose the results.

This is pretty intensive and not something I want enabled on all transfers. Over all, the `destination file exists` retry loop should be rather rare.

**Comment by bari12** [comment] 2021-05-25 13:41
👍 understood. For this to work for Belle II it would need the `file-integrity-report` flag then; Or possibly Belle can also use `check-on-tape`?

**Comment by KatyEllis** [comment] 2021-06-01 14:53
Hi All,
Can I confirm whether this solution will go ahead? And if so, what sort of timescale is likely, e.g. 1 month, 3 months, 6 months..? I realise this is mainly a problem for CMS. The number of failures appears to have multiplied in the last week, attaching an image to illustrate. 
![Screenshot 2021-06-01 at 15 51 03](https://user-images.githubusercontent.com/43205441/120344302-5f7f0980-c2f1-11eb-88bf-3b815bf64420.png)

**Comment by mpatrascoiu** [comment] 2021-06-01 16:53
Hello Katy,

I believe the solution is agreed on. What is yet to be set in stone is the response FTS will give back. We'll have to come up with something that is uniform across SRM and XRootd protocols. Julien's proposal was more extensive, but the minimum I can get by with is:
```json
  "dst_file": {
    "path": "/eos/ctacms/archive/cms/store/mc/RunIISummer20UL18MiniAOD/TTToSemiLeptonic_mtop169p5_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/240000/2CA24833-6D0B-954B-B911-29EC334AE83C.root",
    "path_exists": true,
    "on_tape": true,
    "online": false,
    "error_text": "",
    "filesize": 4189582710,
    "adler32": "453dc8ce"
  }
  ```
  
  In terms of development effort, I estimate we'll have this in 1-2 months' time.
  In terms of deployment, probably beginning of autumn, in accordance with Rucio development availability and holiday interference.
  
  Cheers,
  Mihai

**Comment by bari12** [comment] 2021-06-10 16:48
@cserf @iueda it would be really useful to have your feedback here as well.
In terms of Rucio development, I think a similar time-scale as @mpatrascoiu suggested is doable.

**Comment by iueda** [comment] 2021-06-11 10:17
Let me understand first.
1. There will be the options `check-on-tape` and `--file-integrity-report`, with which FTS will return the metadata of the destination file.
2. If the metadata (size and checksum) are correct, the transfer is considered successful, i.e. the previous _failed_ transfer which made the file is re-evaluated as success.
3. If the metadata are incorrect, there is another option to trigger over-write, i.e. the file there is judged as useless.

Here I have two worries.
For (2), if the previous transfer was a failure, there must have been a reason for that. Can we really blindly trust the metadata that the SE tells without checking the file itself? In addition, files failed in SRM Put Done are often locked in a strange situation and cannot be accessed, even when the size and checksum are correct.
For (3), if we don't set over-write for TAPE endpoints, there are good reasons for that. If we _can_ consider files are invalid when the metadata are different from Rucio's expectation, why don't we set over-write option from the beginning? We don't over-wirte because we consider the files existing there can be valuable even when they are different from what Rucio expects.

That is why we are _renaming_ files in such situation, keeping them on tape, but making way for rucio transferring the files in concern.
Simple renaming does not require `stat` + `checksum` + `xattr user.status` -- yes, I agree it is heavy -- and no judgement on file validity is automatically made.
You may consider changing the piece of the flow chart after "File is corrupted", replacing overwrite with rename, but it addresses only the worry on (3), not the one on (2). And if renaming can be done either by rucio or by FTS, it can be applied not only after  "File is corrupted", but in general after "Error DST exists".

Answering some previous question;
The main TAPE SE for Belle II would not give the `on_tape` status to FTS, so we would not be able to use `check-on-tape` with that SE.
As for `--file-integrity-report`, I agree (as I wrote above) that we don't want to do that after every transfer. Are you suggesting to set this flag only after failed transfers with Destination file exists and overwrite is not enabled error?

**Comment by bari12** [comment] 2021-06-17 13:48
Hi,

Maybe somebody can comment on (2), what possible errors are there and the trustworthiness of the metadata.

In principle, Rucio could also implement a renaming workflow for deterministic RSEs, similar to non-deterministic ones. But it is more cumbersome since Rucio would have to do these renames, which currently it does not.

Anyway, if the suggested workflow is fine for CMS and Belle II has their own (external) renaming workflow, I think we are all set. Optionally, the Belle II renaming could be made Rucio native later as well.

More comments?

**Closed as completed** 2021-10-26 13:27 UTC
Labels: enhancement, Transfers
