### ISSUE TITLE
Checksum display uses scientific notation

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#3365] opened 2020-03-05 14:30 UTC
Motivation
----------

```rucio get-metadata O3:K-K1_llhoft-1266855936-4096.gwf```
```adler32:         030853e9```

leads to the following:

```rucio list-file-replicas O3:K-K1_llhoft-1266855936-4096.gwf
+---------+---------------------------------+------------+------------+-------------------------------------------------------------------------------------------------------------------+
| SCOPE   | NAME                            | FILESIZE   |    ADLER32 | RSE: REPLICA                                                                                                      |
|---------+---------------------------------+------------+------------+-------------------------------------------------------------------------------------------------------------------|
| O3      | K-K1_llhoft-1266855936-4096.gwf | 322.137 MB | 3.0853e+13 | ....               |```


Because there are no letters, the client interprets the string as a number in scientific notation (next to last character is an e).

**Comment by dynamic-entropy** [comment] 2021-03-17 11:29
duplicate of #2258

**Closed as completed** 2021-03-25 09:35 UTC
Labels: bug, Clients
