### ISSUE TITLE
flake8 package update to 3.5.0

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#1012] opened 2018-04-03 08:40 UTC
Motivation
----------
Update to the latest version of flake8(3.5.0) but with it, we have:

```
$ flake8 lib/|wc
     181    1262   12472
```
Mostly  `E722 do not use bare except`. If we ignore this error, we are let with:

```
lib/rucio/tests/test_did.py:385:9: E741 ambiguous variable name 'l'
lib/rucio/client/dq2client.py:1445:13: E741 ambiguous variable name 'l'
lib/rucio/client/dq2client.py:1446:16: E741 ambiguous variable name 'l'
```
Modifcation
------------
- Ignore  E722 in `.flake8` for now
- Fix E741

**Comment by bari12** [comment] 2018-04-03 12:38
This is a duplicate of #195

**Comment by bari12** [comment] 2018-04-03 12:49
Perhaps we should create a second issue so we fix the E722 eventually and don't completely forget about them.

**Comment by vingar** [comment] 2018-04-03 12:49
yes +1

**Closed as completed** 2018-04-11 09:11 UTC
Labels: enhancement, Release management
