### ISSUE TITLE
LocalSite in traces from downloadclient should be RSE, not site.

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2048] opened 2019-01-25 15:23 UTC
Motivation
----------
wrong traces = wrong accounting

Modification
------------
https://github.com/rucio/rucio/blob/master/lib/rucio/common/utils.py#L657
should return another field called 'rse', where rse would be populated. Is that possilbe?

**Comment by mlassnig** [comment] 2019-11-14 16:05
This needs to be fixed in the downstream monitoring. Not a bug on our side, we are reporting correctly the site.

**Closed as completed** 2019-11-14 16:06 UTC
Labels: bug, Clients
