### ISSUE TITLE
Subscription history updates throw unknown database errors

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6351] opened 2023-10-17 02:27 UTC
### Description

- [ ] Keep history config expects a boolean value but wrongly uses config_get instead of config_get_bool, https://github.com/rucio/rucio/blob/6a5ccae83bb0abed78998fb04a20dabb1fdf2ee4/lib/rucio/core/subscription.py#L149C24-L149C34

- [ ] A subscription update results in a database exception when keep_history is set
```bash
rucio-admin subscription update --lifetime 0 .....

Database exception.
Details: An unknown Database Exception has occurred.
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/bin/rucio-admin", line 97, in new_funct
    return function(*args, **kwargs)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/bin/rucio-admin", line 947, in update_subscription
    client.update_subscription(name=args.name, account=account, filter_=json.loads(args.filter), replication_rules=json.loads(args.replication_rules),
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/lib/python3.9/site-packages/rucio/client/subscriptionclient.py", line 144, in update_subscription
    raise exc_cls(exc_msg)
rucio.common.exception.DatabaseException: Database exception.
Details: An unknown Database Exception has occurred.
```

- [ ] The config does not immediately update within the servers and instead the cache value is used for the first attempt after the config change. So, your command will work or not (based on config change) n number of times where n=number of rucio servers.

### Steps to reproduce

1. Set the keep_history option under the subscriptions section of the config. 
` rucio-admin config set --section subscriptions --option keep_history --value True`

2. Try updating any subscription
```python3
client.update_subscription(
     name='MyTestSubscription',
     account = 'rchauhan',
     replication_rules = [{
         'rse_expression':'T2_CH_CERN',
         'copies':1,
         'lifetime': 864000,
         'comment':'test subscription rule',
         'activity': "User Subscriptions"
         }],
     comments = 'Test subscription updated oct 16',
     filter_= {
         'pattern':'txt',
         'did_type':'CONTAINER',
         'scope':['cms']
         },
     lifetime=30
     )
```

**Comment by cserf** [comment] 2023-11-06 13:54
I'm not able to reproduce. Can you check what is the database error on the server side please ? Is it the same error as https://github.com/rucio/rucio/issues/6292 ?

**Comment by bari12** [comment] 2024-05-17 12:51
This is a duplicate of #6292

**Closed as completed by bari12** 2024-05-17 12:51 UTC
Labels: bug, Subscriptions
