### ISSUE TITLE
Add parameters to daemons’ stop() function

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6075] opened 2023-02-08 14:13 UTC
### Description

Per [the documentation](https://docs.python.org/3/library/signal.html?highlight=signal%20signal#signal.signal), the signal handler is expected to have two parameters. Their absence may cause a somewhat-benign unhandled exception.

```
Traceback (most recent call last):
  File "/usr/local/bin/rucio-conveyor-preparer", line 26, in main
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    thr.join(timeout=3.14)
  File "/usr/local/bin/rucio-conveyor-preparer", line 37, in <module>
    run(once=args.run_once, threads=args.threads, sleep_time=args.sleep_time, bulk=args.bulk)
  File "/usr/lib64/python3.6/threading.py", line 1060, in join
    elif lock.acquire(block, timeout):
TypeError: stop() takes 0 positional arguments but 2 were given
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/conveyor/preparer.py", line 70, in run
    main(args=parser.parse_args())
```

### Steps to reproduce

The above-provided traceback was noticed on the ATLAS instance. It is unknown whether it is always reproducible when shutting down daemons.

**Comment by shalearkane** [comment] 2023-02-12 20:58
Hey, if this issue is not assigned to anyone, can I work on this?

**Comment by shalearkane** [comment] 2023-02-15 06:36
I failed to reproduce the issue. I followed the instructions [here](https://github.com/rucio/rucio/tree/master/etc/docker/dev) and I ran the `run_daemons` command in the `dev-rucio-1` container. I tried to terminate the command using `^C` multiple times however I was unable to reproduce it. Could it be because in the ATLAS instance, it is using a different kill signal?

**Comment by dchristidis** [comment] 2023-02-15 08:51
`^C` sends a `SIGINT`, not a `SIGTERM`. Here’s a minimal example demonstrating the issue.

```console
$ cat foo.py
#!/usr/bin/env python3

import signal
import time

def stop():
    print('stop')

if __name__ == '__main__':
    signal.signal(signal.SIGTERM, stop)
    try:
        while True:
            time.sleep(60)
    except KeyboardInterrupt:
        stop()
$ python3 foo.py 
^Cstop
$ python3 foo.py &
[1] 168059
$ kill 168059
Traceback (most recent call last):
  File "/var/home/dchristidis/foo.py", line 13, in <module>
    time.sleep(60)
TypeError: stop() takes 0 positional arguments but 2 were given
```

**Closed as completed** 2023-07-03 09:09 UTC
Labels: bug, Documentation, good first issue, ❤️ help welcome ❤️
