### ISSUE TITLE
Tests: download pfns is flaky

### ISSUE THREAD

**Issue by voetberg** [rucio/rucio#6534] opened 2024-03-06 17:40 UTC
### Description

Tests sometimes fail because `TestBinRucio.test_download_pfn` fails, regardless of if the code changed impacts it or not. This test should be marked as flaky and auto-retried (or xfail'd), or else fixed. Seems to be more an issue relating to the gh action runner than the test itself. 

Examples: https://github.com/rucio/rucio/actions/runs/8175076020/job/22351491952 , https://github.com/rucio/rucio/actions/runs/8175076020/job/22351491952 , https://github.com/rucio/rucio/actions/runs/7991176001/job/21821749554

### Steps to reproduce

1. Make a pull request 
2. Refresh tests until `TestBinRucio.test_download_pfn` fails

**Comment by rdimaio** [comment] 2024-03-07 11:44
Duplicate of https://github.com/rucio/rucio/issues/6506

**Closed as completed** 2024-03-07 13:23 UTC
Labels: bug, Testing
