### ISSUE TITLE
More information in "server certificate expired" output

### ISSUE THREAD

**Issue by deesto** [rucio/rucio#5021] opened 2021-11-17 21:56 UTC
https://github.com/rucio/rucio/blob/63823eceebe68294c98364884a33172d14591da9/bin/rucio#L284

Would it be possible to include the literal server DN(/CA) string in the error given when a server-side certificate failure is detected? This would be much more useful than the generic string "The server certificate expired.", especially when it may not be the case that the server certificate has expired. We experienced a problem with refreshing and accessing CRL and related signing files, and while the server certificate and chain remained valid, clients saw the following:
`2021-11-18 01:57:16,518	ERROR	Cannot authenticate.
Details: HTTPSConnectionPool(host='{rucio_server}', port=443): Max retries exceeded with url: /auth/x509_proxy (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:661)'),))
2021-11-18 01:57:16,522	ERROR	The server certificate expired.`

Since we saw nothing wrong on the server side, had this output been more descriptive, we might have been able to solve the issue in a fraction of the time.

Thanks!

**Comment by deesto** [comment] 2021-11-22 16:07
Actually, we continue to see this issue intermittently, including now, and we see no problems on the server side -- is there any way of debugging this?

**Comment by joeldierkes** [comment] 2021-11-24 14:00
@deesto Could you be so kind and pass the output of the command you used with the `--verbose` flag right after `rucio`?
```
rucio --verbose ...
```

**Comment by deesto** [comment] 2021-11-24 14:16
@joeldierkes I will be happy to, if we are able to reproduce this again! It has been happening intermittently over the past week. Previously, I was able to trigger it by removing my own cached client token (`rm /tmp/${user_id}/.rucio_${rucio_id}/auth_token_${rucio_id}`), but that doesn't seem to be triggering the problem today. On the server side, I believe the only changes we've made were to remove cached `mod_gridsite` credentials and then restart `httpd`.

**Comment by joeldierkes** [comment] 2021-11-24 14:46
@deesto Okay.
The response of the server is already logged as debug message if there was an error:
https://github.com/rucio/rucio/blob/b820877f58c975740d9ea1fd448c3dcf2eb013cf/lib/rucio/client/baseclient.py#L430

Please use the `--verbose` flag the next time you encounter the problem and comment on this issue if it was helpful/what else should be logged.

**Comment by deesto** [comment] 2021-11-24 15:14
Thanks @joeldierkes. I see. I wish i had known that or thought to use `--verbose` earlier. I'll do that and report back at the next opportunity. Still, the error is somewhat vague and possibly misleading, as there is no issue with the server certificate itself.

**Comment by joeldierkes** [comment] 2021-11-24 15:19
@deesto You're totally right, the error message is misleading. I will act on that once I was able to reproduce the error, to which the debug output would definitely be helpful.

I don't know how to properly write this, but let's hope that your client crushes again? 😄

**Comment by deesto** [comment] 2021-11-24 15:26
LOL understood! It wasn't my client that crashed originally -- we were just troubleshooting a user report and were able to reproduce the problem. Initially, we thought `fetch-crl` was hanging on the servers and causing related signed certificates to fail, but that may be false. And for some time, I was able to reliably reproduce the error as mentioned. At this point we can only guess that there is some combination of cached credentials on the server, or client or both, that causes this error.

**Comment by joeldierkes** [comment] 2021-11-24 15:47
@deesto Okay, use this issue if you have further questions/insights.

**Comment by deesto** [comment] 2021-11-26 15:02
@joeldierkes Unfortunately this is happening again, intermittently. And unfortunately, adding the `--verbose` flag did not help at all -- only the same error was shown, with no additional detail. By the time I ran the client tools again with `strace`, the error disappeared, with no action taken on either side.

I see that when `ping` succeeds, `--verbose` adds only a timestamp. I am not sure on what that timestamp is based. For example, this command took several seconds to return, possibly 10 or more:
```
$ rucio --verbose ping

1.26.4
Completed in 0.4765 sec.
```
It definitely didn't complete in 0.5s. Knowing where the delay was might help us track down this issue.

**Comment by deesto** [comment] 2021-11-26 15:19
```
-bash-4.2$ rucio --verbose whoami
2021-11-26 09:46:31,402	ERROR	Cannot authenticate.
Details: HTTPSConnectionPool(host='blrucio.sdcc.bnl.gov', port=443): Max retries exceeded with url: /auth/x509_proxy (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:661)'),))
2021-11-26 09:46:31,403	ERROR	The server certificate expired.
-bash-4.2$
```

**Comment by deesto** [comment] 2021-11-26 15:35
```
-bash-4.2$ time rucio --verbose ping
1.26.4
Completed in 0.4417 sec.

real	0m3.977s
user	0m0.988s
sys	0m0.429s
-bash-4.2$
```

**Comment by joeldierkes** [comment] 2021-11-26 16:07
@deesto I looked into that, and the `--verbose` flag does not change the logger instance of the Python Client in version `1.26.4`.

Could you add
```
[logging]
forceloglevelDEBUG=rucio.client.baseclient
```
to your client's `rucio.cfg` file? This sets the clients log level to `DEBUG` in 1.26.4.

I tested it with the version, this one works. Sorry for the inconvenience.

**Comment by joeldierkes** [comment] 2021-11-26 16:11
FYI this was changed in #4220 and will be merged into version `1.27.0`. This means that you can use `rucio --version ...` in version `1.27.0` to change the log level to `DEBUG`.

**Comment by deesto** [comment] 2021-11-26 16:27
Thanks. So far, the workaround to fix this seems to be to remove the client-side Rucio user token:
`rm -rf /tmp/$(whoami)/.rucio_*`

**Comment by deesto** [comment] 2021-11-30 21:36
Actually, what really works is restarting httpd on the Rucio server, often enough to load refreshed CA and CRL files.

**Comment by bari12** [comment] 2021-12-01 15:22
That sounds like some kind of issue with your httpd/host certificates, what do the server logs say?

**Comment by deesto** [comment] 2021-12-01 17:15
Not much at all. We assume that httpd does not reload or refresh CA and CRL files until its service is restarted, no matter how often they are refreshed on the system. This seems to be confirmed in [a very long running bug discussion](https://bz.apache.org/bugzilla/show_bug.cgi?id=14104). This might explain why no errors are seen on the server, yet Rucio rejects token requests for clients with certificates from CAs with "expired" CRL files.

**Comment by bari12** [comment] 2021-12-03 15:37
But are the CA/CRL files you use so short-lived? I am wondering why this is a recurring problem.

**Comment by deesto** [comment] 2021-12-03 20:50
We're not sure either. This is precisely why it would be helpful to know exactly what "server certificate expired," when it is certainly not that of our Rucio servers.

**Comment by bari12** [comment] 2021-12-04 08:44
Did you check the client certificate(s)?
While `SSLV3_ALERT_CERTIFICATE_EXPIRED` usually points to the server certificate, I imagine it might actually also be the client certificate.
The message `ERROR The server certificate expired.` comes from the rucio clients (thus from us) when the `SSLV3_ALERT_CERTIFICATE_EXPIRED` is raised, but it might actually be a red herring here.

**Comment by deesto** [comment] 2021-12-06 13:55
Yes, unfortunately, this error is not linked to client proxy expiration. I have confirmed this myself many times now with my own valid proxy.

**Comment by bari12** [comment] 2021-12-06 15:57
I would try to debug this outside of Rucio, to try to get some more information. Going with curl with maximum verbosity (and the proxy/certificate) directly against the `/auth/x509_proxy` REST endpoint and see what the log/server log says.

**Comment by deesto** [comment] 2021-12-15 20:01
Outside of Rucio (or directly related as dependencies), this seems due to some sync or conflict involving OpenSSL, NSS, CRLs, and httpd. If we ensure httpd is always restarted immediately after a CRL refresh, the problem is not seen. For completeness, the other variant here from ATLAS is B2 deals with a custom DIRAC component for auth, but that may not be related.

**Comment by bari12** [comment] 2022-01-10 09:49
I'll close this for now since there is nothing clearly actionable from our side. Feel free to re-open/add information to this ticket though.

**Closed as completed by bari12** 2022-01-10 09:49 UTC
Labels: enhancement, Clients
