### ISSUE TITLE
Setting replicas to `BAD` or `TEMPORARY_UNAVAILABLE` also needs to update their collection_replicas

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3526] opened 2020-04-23 09:41 UTC
Motivation
----------
Both the oracle procedure as well as the abbacus daemon need to consider TU replicas. These should be handled similar to AVAILABLE replicas.

**Comment by bari12** [comment] 2022-10-18 08:27
Oracle procedure actually seems to be fine, since it filters to `A` replicas, but the workflow of setting a replica to `TEMPORARY_UNAVAILABLE` or `BAD`  needs to add a `updated_collection_replica` to trigger a dataset replica update.
The issue is that the replicas need to be correlated to the datasets, which might be expensive.

**Comment by bari12** [comment] 2022-10-18 08:37
Need to check if necromancer resolves datasets, if yes, this should be as easy as adding a `updated_collection_replica` for these datasets.

**Comment by cserf** [comment] 2022-10-27 09:41
The problem is not the `necromancer` but `minos`. The datasets containing the files are not resolved. As you mentioned, resolving them would be an expensive operation which would slow down a lot `minos`. Do we really need it ?

**Comment by cserf** [comment] 2022-11-01 08:29
Doing extra check on the necromancer. There are 2 methods used by the necromancer depending if the file is recoverable or not : 
- `update_rules_for_bad_replica` in case the replica is recoverable. This method already insert a row in `UpdatedCollectionReplica` : https://github.com/rucio/rucio/blob/9dc4238217a37b938f120b3bac2007487f6a063e/lib/rucio/core/rule.py#L1814 so it should be OK
- `update_rules_for_lost_replica` in case of lost files. This one relies on `rucio.core.did.detach_dids`. There is nothing done to insert a row into `UpdatedCollectionReplica` directly in this method, but it inserts into `UpdatedDID`. That means that the collection replica might be fix by the `judge-repairer` @bari12 can you confirm please ? But we still have a problem if the replica was not covered by a rule.

**Comment by bari12** [comment] 2024-04-26 14:50
Will be irrelevant once we fully remove collection replicas.

**Closed as not planned** 2024-04-26 14:50 UTC
Labels: enhancement, Replicas
