### ISSUE TITLE
`datetime.utcnow()` is deprecated

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6553] opened 2024-03-13 13:29 UTC
### Description

```
The method "utcnow" in class "datetime" is deprecated
  Use timezone-aware objects to represent datetimes in UTC; e.g. by calling .now(datetime.UTC)
```

there are 333 instances of `datetime.utcnow()` in `rucio/rucio` as of creating this issue.

### Steps to reproduce

N/A

**Comment by dchristidis** [comment] 2024-03-13 13:33
Duplicate of #6476.

**Closed as not planned by dchristidis** 2024-03-13 13:33 UTC
Labels: enhancement, good first issue
