### ISSUE TITLE
rucio list-rse-usage  --show-accounts sometimes crashes with Internal Error

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2103] opened 2019-02-04 12:34 UTC
Motivation
----------
`rucio list-rse-usage  --show-accounts` sometimes crashes with `Internal Error`. The problem is due to division by zero on the server side :
```
[Mon Feb 04 13:31:23.641239 2019] [:error] [pid 18854:tid 139955217078016] float division by zero
[Mon Feb 04 13:31:23.644559 2019] [:error] [pid 18854:tid 139955217078016] Traceback (most recent call last):
[Mon Feb 04 13:31:23.644574 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/rucio/web/rest/rse.py", line 614, in GET
[Mon Feb 04 13:31:23.644578 2019] [:error] [pid 18854:tid 139955217078016]     usage = get_rse_usage(rse, issuer=ctx.env.get('issuer'), source=source, per_account=per_account)
[Mon Feb 04 13:31:23.644580 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/rucio/api/rse.py", line 265, in get_rse_usage
[Mon Feb 04 13:31:23.644583 2019] [:error] [pid 18854:tid 139955217078016]     return rse_module.get_rse_usage(rse=rse, source=source, per_account=per_account)
[Mon Feb 04 13:31:23.644589 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
[Mon Feb 04 13:31:23.644592 2019] [:error] [pid 18854:tid 139955217078016]     return Retrying(*dargs, **dkw).call(f, *args, **kw)
[Mon Feb 04 13:31:23.644594 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
[Mon Feb 04 13:31:23.644596 2019] [:error] [pid 18854:tid 139955217078016]     return attempt.get(self._wrap_exception)
[Mon Feb 04 13:31:23.644599 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
[Mon Feb 04 13:31:23.644601 2019] [:error] [pid 18854:tid 139955217078016]     six.reraise(self.value[0], self.value[1], self.value[2])
[Mon Feb 04 13:31:23.644603 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
[Mon Feb 04 13:31:23.644605 2019] [:error] [pid 18854:tid 139955217078016]     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
[Mon Feb 04 13:31:23.644607 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 270, in new_funct
[Mon Feb 04 13:31:23.644609 2019] [:error] [pid 18854:tid 139955217078016]     return function(*args, **kwargs)
[Mon Feb 04 13:31:23.644612 2019] [:error] [pid 18854:tid 139955217078016]   File "/usr/lib/python2.7/site-packages/rucio/core/rse.py", line 568, in get_rse_usage
[Mon Feb 04 13:31:23.644614 2019] [:error] [pid 18854:tid 139955217078016]     account_usages.append({'used': row.bytes, 'account': row.account, 'percentage': round(float(row.bytes) / float(total) * 100, 2)})
[Mon Feb 04 13:31:23.644616 2019] [:error] [pid 18854:tid 139955217078016] ZeroDivisionError: float division by zero
```

**Comment by bari12** [comment] 2019-02-04 12:37
Duplicate of #2040 - It's fixed in 1.19.0

**Closed as completed by bari12** 2019-02-04 12:37 UTC
Labels: bug, Core & Internals
