### ISSUE TITLE
Probe to automatically recover suspicious files that have multiple replicas

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1871] opened 2018-12-05 12:36 UTC
Motivation
----------
For the suspicious files that have multiple replicas, there is no need of human check to confirm that the replica is actually bad. One can have a probe to automatically recover them.

**Comment by bari12** [comment] 2018-12-05 12:39
Isn't this a duplicate of #403 
I also don't think this should be a probe, but a service/daemon, since it is really a central functionality. Or do you suggest to do a probe first and the service later?

**Comment by cserf** [comment] 2018-12-05 12:41
Ah, right I forgot about the other ticket. I'm not sure it deserves to be a daemon.

**Comment by bari12** [comment] 2018-12-05 12:49
I think we should aim to have these functional parts, which are potentially useful for a wider audience, as daemons; We should try to get away from probes for these things.

**Closed as completed** 2018-12-10 12:21 UTC
Labels: enhancement
