### ISSUE TITLE
update_replication_rule returns "internal server error" when updating lifetime

### ISSUE THREAD

**Issue by sartiran** [rucio/rucio#505] opened 2018-01-22 16:20 UTC
Motivation
----------
On the client side:
>>> from rucio.client.ruleclient import RuleClient
>>> r = RuleClient()
>>> r.update_replication_rule('ebb0750fbb4b46678bb0d49cdba1f6c3',{'lifetime': 10000})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 123, in update_replication_rule
    exc_cls, exc_msg = self._get_exception(headers=r.headers, status_code=r.status_code, data=r.content)
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 212, in _get_exception
    data = parse_response(data)
  File "/usr/lib/python2.7/site-packages/rucio/common/utils.py", line 213, in parse_response
    return json.loads(data, object_hook=datetime_parser)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

the JSON that cannot be decoded is "internal server error"

Looking at the apache logs on server side:

[Mon Jan 22 10:02:47.071115 2018] [:error] [pid 6857] [client 134.158.132.125:54212]     update_replication_rule(rule_id=rule_id, options=options, issuer=ctx.env.get('issuer'))
[Mon Jan 22 10:02:47.071119 2018] [:error] [pid 6857] [client 134.158.132.125:54212]   File "/usr/lib/python2.7/site-packages/rucio/api/rule.py", line 171, in update_replication_rule
[Mon Jan 22 10:02:47.071124 2018] [:error] [pid 6857] [client 134.158.132.125:54212]     rule.update_rule(rule_id=rule_id, options=options)
[Mon Jan 22 10:02:47.071128 2018] [:error] [pid 6857] [client 134.158.132.125:54212]   File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 349, in new_funct
[Mon Jan 22 10:02:47.071132 2018] [:error] [pid 6857] [client 134.158.132.125:54212]     result = function(*args, **kwargs)
[Mon Jan 22 10:02:47.071136 2018] [:error] [pid 6857] [client 134.158.132.125:54212]   File "/usr/lib/python2.7/site-packages/rucio/core/rule.py", line 1112, in update_rule
[Mon Jan 22 10:02:47.071141 2018] [:error] [pid 6857] [client 134.158.132.125:54212]     rule.expires_at = datetime.utcnow() + timedelta(seconds=lifetime) if options['lifetime'] is not None else None
[Mon Jan 22 10:02:47.071146 2018] [:error] [pid 6857] [client 134
[5:07 PM]
TypeError: unsupported type for timedelta seconds component: NoneType

Following Vincent Garonne suggestion I fill an issue as this seems a bug.

Modification
------------

Expected behavior
-----------------

**Comment by bari12** [comment] 2018-01-23 15:32
I cannot reproduce this bug

```
from rucio.client.ruleclient import RuleClient
r = RuleClient()
r.update_replication_rule('ee0ab3b8547749ac964aaa5849d69857',{'lifetime': 10000})
True
```

I wonder if this is due to some version difference. What client/server version are you using?

**Comment by sartiran** [comment] 2018-01-23 15:41
1.14.7 I'm re-building the docker to get up to date stuff, then I'll re-test

**Comment by sartiran** [comment] 2018-01-23 15:57
well, after updating I ended up with the very same version.
But I still see the same error
>>> from rucio.client.ruleclient import RuleClient
>>> r=RuleClient()
>>> r.update_replication_rule('1b04a48135d0402894e64541dbec3f0c',{'lifetime': 10000})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 122, in update_replication_rule
    exc_cls, exc_msg = self._get_exception(headers=r.headers, status_code=r.status_code, data=r.content)
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 211, in _get_exception
    data = parse_response(data)
  File "/usr/lib/python2.7/site-packages/rucio/common/utils.py", line 213, in parse_response
    return json.loads(data, object_hook=datetime_parser)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

**Comment by bari12** [comment] 2018-01-23 16:04
Ok, I need to do some more digging then 😄

**Comment by bari12** [comment] 2018-01-24 14:37
I still cannot reproduce this 😞 , I suspect this is a problem with the json decoder or apache. Can you add a `print options` before https://github.com/rucio/rucio/blob/master/lib/rucio/core/rule.py#L1112 and show the output from the log.
Alternatively you can also give me access to the machine.

**Comment by sartiran** [comment] 2018-01-24 18:05
HI, I'm confused. I cannot find the rule.py file. Are you talking of client side or server side?

**Comment by bari12** [comment] 2018-01-25 11:39
Server side, depending on the location of the code it should be in the lib/rucio/core/ subdirectory.

**Comment by sartiran** [comment] 2018-01-25 12:53
OK. I've no access to server. Maybe we should ask Brian? One point is not clear to me. This is a client side problem, right (or at least it is in the client the difference that generate the problem)?  Have you tried to reproduce it using Eric docker client environment? Maybe different versions of packages?

**Comment by bari12** [comment] 2018-01-25 13:30
I have only tested with the same version on my dev machine, but not the docker client yet. 
I am not sure if it is a client or server problem, both is possible, on the server it could be some combination between httpd and the json decoder of the exact python version which leads to a different unpacking of this dictionary. On the client side it could also be the python version and json encoder which packs the data somehow differently so the server cannot unpack it. But it is just guessing basically. 
What I see in the log is that on the server the dictionary gets unpacked in a way that lifetime is a NoneType, (so not None, but NoneType, which is a json thing). I have to try it with the docker images.

**Comment by bari12** [comment] 2018-05-29 14:17
Hi @sartiran,
This ticket is quite old now but just to make a quick follow up on it: did you experience this bug in any of the newer version (1.16.0+)?

**Comment by sartiran** [comment] 2018-05-29 14:19
I'm quite sure it is fine now. I'll double-check asap and, if it is, I'll close the issue

**Comment by bari12** [comment] 2018-07-26 13:02
Hi @sartiran I am closing this now. If the problem shows up again, please open another ticket 😄

**Closed as completed by bari12** 2018-07-26 13:02 UTC
Labels: bug, Rules
